### ISSUE TITLE
Yup shows AUR packages to "downgrade"

### ISSUE THREAD

**Issue by faasie** [ericm/yup#10]
YUP will show packages that were locally built (newer) than their AUR counterparts and ask if you want to "update" those packages:
![image](https://user-images.githubusercontent.com/4673577/61424929-2eef7b80-a8e3-11e9-99c9-bb538f4e2956.png)

Using YAY, it will show that the local packages are newer, but will not prompt to update.
![image](https://user-images.githubusercontent.com/4673577/61424973-5ba39300-a8e3-11e9-89be-4a9780e64638.png)

It would nice to be able to either set a config option or have a similar experience to YAY.

I like YUP! MUCH easier to search AUR.

Thanks!

**Comment by ericm** [comment]
So this is an issue with displaying the actual version. In reality, it actually will upgrade the package. So I'll fix the display in the next update.

**Comment by ericm** [comment]
I've looked into this issue and it will be fixed in the next update

**Comment by faasie** [comment]
Sounds great!

It certainly wasn't a deal-breaker for me at all but figured I'd let you know.

Thanks!

**Comment by Atemu** [comment]
It still does this for me:

```
==> Updating from local repositories
:: Synchronizing package databases...
 core                                                                  133.7 KiB  3.96M/s 00:00 [########################################################] 100%
 extra                                                                1629.2 KiB  9.36M/s 00:00 [########################################################] 100%
 community                                                               4.9 MiB  12.7M/s 00:00 [########################################################] 100%
 multilib                                                              171.3 KiB  27.9M/s 00:00 [########################################################] 100%
:: Starting full system upgrade...
 there is nothing to do
==> Checking for AUR updates...

==> Found 1 local package(s) that are newer than their AUR package
    simple-mtpfs-git  r107.1482668661.c9a691f-1 has AUR version r1-1

==> Found 6 AUR package(s) to update:
    1   auracle-git r276.176a603-1 -> r258.ab0e8d9-1
    2   based-connect-git r127.335c665-1 -> r79.2f5c7ff-1
    3   fwts-git 4365.603c23fd-1 -> 4336.f4063ed2-1
    4   htop-vim-git 1077.402e46b-1 -> 981.e3f65c8-1
    5   neovim-plug-git r622.226d6ab-1 -> r608.e6a775e-1
    6   solvitaire-git r141.329ade1-1 -> r125.680da21-1
==> Packages not to install? (eg: 1 2 3, 1-3 or ^4): 
```

Since these are all -git packages I'm guessing yup only checks the pkgver in the AUR instead of the source git repos in the PKGBUILDs.
