### ISSUE TITLE
Cannot install/update PhpStorm

### ISSUE THREAD

**Issue by pavlo-nahorniak** [ericm/yup#23]
Hi there, I`ve been getting these error for more then half year every time I want to update phpstorm
```
==> Starting package_phpstorm()...
cp: cannot stat '/home/pnagornyak/.cache/yup/phpstorm/src/PhpStorm-193.5233.101PhpStorm/': No such file or directory
==> ERROR: A failure occurred in package_phpstorm().
    Aborting...
==> exit status 4
```
I don`t really know what can cause such issue, but if I download PKGBUILD from AUR and just build it manually everything works, could you help me find out what is wrong here?

**Comment by Thomas007G** [comment]
Hello, try clearing your cache in the current version using `yup -c`, and let us know if the error continues.

**Comment by ericm** [comment]
This can be caused if there was some previous failure with the install of the package as binaries and directories may be half built and that may confuse makepkg the next time it tries to build.

**Comment by ericm** [comment]
Clearing cache deletes everything in ~/.cache/yup that's not being tracked by the git repo cloned from the AUR which should fix this. If you just wish to clear this directory, `yup -C` will do so as `yup -c` also clears pacman cache

**Comment by pavlo-nahorniak** [comment]
Yes, the issue was in cache, `yup -C` or `yup -c` does not help, only manually deleting of `~/.cache/yup` folder, now everything works perfectly. Thanks for helping me.

Consider adding **Troubleshooting** section to the readme file.

**Comment by ericm** [comment]
I've never had an install issue that `yup -C` didn't fix. It's strange that you had to delete the folder. My only guess is that there was something up with that AUR package.
