### ISSUE TITLE
Some AUR packages are in to update instead of previous section

### ISSUE THREAD

**Issue by kepi** [ericm/yup#31]
I have multiple packages installed from AUR which are offered for update every time I run `yup` but IMHO they shouldn't.

I.e. in todays output:

```
==> Checking for AUR updates...

==> Found 2 local package(s) that are newer than their AUR package
    numix-icon-theme-pack-git  r6767-1 has AUR version r6086-1
    ttf-consolas-with-yahei-powerline-git  r.-1 has AUR version r14.b6e9163-1

==> Found 7 AUR package(s) to update:
    1   mbsync-git 946.cab1460-1 -> 912.95d18e2-1
    2   mu-git 1.4.7.119.g6cea9fcd-1 -> 1.3.6.114.g0dced59c-1
    3   qutebrowser-git 1.13.1.r269.gcee5d0b0d-1 -> 1.13.0.r2.gcb15192cd-1
    4   screenkey-git 1.1.r12.ge812693-1 -> 1.1.r5.g467662b-1
    5   ttf-iosevka-ss05 3.3.0-1 -> 3.3.1-1
    6   ttf-iosevka-term-ss05 3.2.2-1 -> 3.3.1-1
    7   ttf-nerd-fonts-hack-complete-git 20200723-1 -> 20180330-1
```

I believe that 1, 2, 3, 4 and 7 are more recent then AUR versions and should be in "found X local pcakges that are newer" section.

If I'm right, it seems that `newerVersion` function might be to blame: https://github.com/ericm/yup/blob/eb8e4e89760cb792e4e5f3b4a153e8069efa5aa7/update/update.go#L154

I'm not really fluent in Go and I'm not sure if I'm correct so no pull request (at least for now).

Thanks

**Comment by yochananmarqos** [comment]
Bumping this as `yup` is completely useless for update AUR VCS (devel) packages. It thinks the version in the AUR is newer no matter what version is installed.

**Comment by Ballasi** [comment]
For some reason, there are values a and b that returns true for both `newerVersion(a, b)` and `newerVersion(b, a)` calls.

I have been working on an implementation that would solve this problem, I have rewritten the function entirely. I have done some tests to try out the implementation, you can find it here: https://go.dev/play/p/QUm8zPl_Ngw

Hope that helps!

**Comment by ericm** [comment]
> For some reason, there are values a and b that returns true for both `newerVersion(a, b)` and `newerVersion(b, a)` calls.
> 
> I have been working on an implementation that would solve this problem, I have rewritten the function entirely. I have done some tests to try out the implementation, you can find it here: https://go.dev/play/p/QUm8zPl_Ngw
> 
> Hope that helps!

This looks great! I'll get reviewing #39
