### ISSUE TITLE
`yup wxhexeditor` fails but `yay wxhexeditor` works.

### ISSUE THREAD

**Issue by SBhojani** [ericm/yup#33]
[![asciicast](https://asciinema.org/a/c4GLlqdQ5fRB2nauuJ83X8xZB.svg)](https://asciinema.org/a/c4GLlqdQ5fRB2nauuJ83X8xZB)

**Comment by Thomas007G** [comment]
Hey, are you on the latest version

**Comment by ericm** [comment]
Could you `yup -V`  and give the output?

**Comment by Thomas007G** [comment]
works for me on latest version `1.1.6`

**Comment by gall** [comment]
closed as working on latest version
