### ISSUE TITLE
Cannot Install via yay on Manjaro ARM (Raspberry Pi 4b)

### ISSUE THREAD

**Issue by johntdavis84** [ericm/yup#36]
## Are you on latest version of yup?
Yes

## Steps to Reproduce the Problem
_Meanwhile, on my new 8GB Raspberry Pi 4b running 64-bit Manjaro Linux..._

  1. `] yay yup` 
  1. Choose `1` --> `aur/yup`
  1. `Yay` attempts to install `yup` and fails with this error:

```
Cloning into 'yup'...
done.
Switched to a new branch 'makepkg'
==> Starting prepare()...
go get
go: downloading github.com/Jguer/go-alpm v0.0.0-20191122171459-5cffc6e8fc69
go: downloading github.com/ericm/goncurses v0.0.0-20190629180204-4f42246a7bb5
go: downloading github.com/mikkeloscar/aur v0.0.0-20190424180024-f956f121b3fa
go: downloading github.com/Morganamilo/go-srcinfo v1.0.0
# github.com/Jguer/go-alpm
../../../../../go/pkg/mod/github.com/!jguer/go-alpm@v0.0.0-20191122171459-5cffc6e8fc69/handle.go:430:10: could not determine kind of name for C.alpm_option_get_arch
../../../../../go/pkg/mod/github.com/!jguer/go-alpm@v0.0.0-20191122171459-5cffc6e8fc69/handle.go:436:10: could not determine kind of name for C.alpm_option_set_arch
make: *** [Makefile:10: build] Error 2
==> ERROR: A failure occurred in prepare().
    Aborting...
error making: yup
```

## Other Details
1. Running `sudo yay` failed with an error. Apparently you're not supposed to do this.
2. I'm new to yay, since the cli version of pamac is not an option on this Pi, and I'm not sure how to tell if I'm actually supposed to be able to build this on an ARMv8 (64-bit) device.

Thanks!

**Comment by ericm** [comment]
The yup aur package is only complied for x86-64. Could you try install
yup-git from the air?

**Comment by johntdavis84** [comment]
Thanks!

It failed again, but it also looked like it was using the previously downloaded files from my earlier attempt to build.

Is there a `yay` command to clear out all the previous build files?

(I’ve never used `yay` until today.)

[Aur:1]  yup-git-v0.1.8.beta.r1.gb764aa8-1

:: Downloaded PKGBUILD (1/1): yup-git
  1 yup-git                          (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> N
:: (1/1) Parsing SRCINFO: yup-git
==> Making package: yup-git v0.1.8.beta.r1.gb764aa8-1 (Sat 28 Aug 2021 08:33:13 PM CDT)
==> Retrieving sources...
  -> Cloning yup git repo...
Cloning into bare repository '/home/victorsuede2011/.cache/yay/yup-git/yup'...
remote: Enumerating objects: 1569, done.
remote: Counting objects: 100% (196/196), done.
remote: Compressing objects: 100% (134/134), done.
remote: Total 1569 (delta 89), reused 152 (delta 60), pack-reused 1373
Receiving objects: 100% (1569/1569), 7.38 MiB | 13.77 MiB/s, done.
Resolving deltas: 100% (741/741), done.
==> Validating source files with sha256sums...
    yup ... Skipped
==> Making package: yup-git v0.1.8.beta.r1.gb764aa8-1 (Sat 28 Aug 2021 08:33:16 PM CDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating yup git repo...
Fetching origin
==> Validating source files with sha256sums...
    yup ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of yup git repo...
Cloning into 'yup'...
done.
==> Starting pkgver()...
==> Updated version: yup-git v1.1.6.r1.g27694a2-1
==> Sources are ready.
==> Making package: yup-git v1.1.6.r1.g27694a2-1 (Sat 28 Aug 2021 08:33:22 PM CDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting pkgver()...
==> Starting build()...
go get
# github.com/Jguer/go-alpm
..***@***.***/handle.go:430:10: could not determine kind of name for C.alpm_option_get_arch
..***@***.***/handle.go:436:10: could not determine kind of name for C.alpm_option_set_arch
make: *** [Makefile:10: build] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
error making: yup-git

**Comment by ericm** [comment]
Try `yay -c`

**Comment by johntdavis84** [comment]
Hello,

I ran yay -c and then yay -S yep, and got the same error.

Would it help if I got it to show diffs, and then posted those here?

						- J.

**Comment by ericm** [comment]
Hi, I've updated yup. Could you try installing again?

**Comment by johntdavis84** [comment]
Sure! I really appreciate you working on this.

On Manjaro, accessing the AUR via yay, I’m seeing two providers: yup and yup-git.

Which one would you like me to test? 

Also, what’s the command I should use to clear out any previously installed bits? I did a yay -c the other day, and it did quite a bit more than I thought it would. Is that the best way to go about it?

**Comment by ericm** [comment]
yup or yup-bin are both maintained by me. Either of them will do.

**Comment by johntdavis84** [comment]
Good afternoon!

It got all the way through the installer, at any rate. It seemed to install a version of go, and then remove it. Not sure what happened there.

Looks like it worked!

❯ yup
==> Updating from local repositories
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 manjaro-arm-games is up to date
:: Starting full system upgrade...
 there is nothing to do
==> Checking for AUR updates...

==> Found no AUR packages to update

Thanks again for all your help.
