### ISSUE TITLE
Possible to use yup in podman/docker?

### ISSUE THREAD

**Issue by i2** [ericm/yup#41]
## Are you on latest version of yup?
Yes/No

## Steps to Reproduce the Problem

  1. podman run -it archlinux
  2. pacman -S openssl wget
  3. wget https://github.com/ericm/yup/releases/download/v1.1.8/yup
  4. yup prompts "No need to run yup as sudo/root"

I know there might be a way to have container use a user other than "root", but I would like a less hacky way to use an AUR helper in a container.

**Comment by ericm** [comment]
The reason why yup blocks running as root is due to its dependency on `makepkg`, which also blocks root:
![image](https://user-images.githubusercontent.com/29894839/166290814-6c7b291b-d4d1-4543-82de-11884ecf15c0.png)

**Comment by i2** [comment]
Yes. I was wondering if you came up with a workaround. Thank you.

**Comment by ericm** [comment]
No, unfortunately there isn't really a way to fix this without increasing the scope of the project exponentially.
